version: '3.8'

services:
  app:
    build: .
    image: yeeloman/my-image-name
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    ports:
      - "8080:8080"